---
- hosts: all
  tasks:
   - name: Install Nginx
     apt: pkg=nginx state=present update_cache=true
  become: yes
  become_method: sudo
  handlers:
   - name: Start Nginx
     service: name=nginx state=started
