---
- hosts: localhost
  connection: local
  tasks:
  - name: Create virtual machine
    azure_rm_virtualmachine:
     resource_group: "{{ vm_resource_group }}"
     name: "{{ vm_name }}"
     vm_size: Standard_D1
     ssh_password_enabled: true
     admin_username: "{{ vm_admin_username }}"
     admin_password: "{{ vm_admin_password }}"
     image:
       offer: UbuntuServer
       publisher: Canonical
       sku: '16.04-LTS'
       version: latest

