---
- hosts: localhost
  connection: local
  tasks:
    # Create a Resouce Group
    - name: Create Resource Group
      azure_rm_resourcegroup:
        state: present
        location: "{{ deploy_group_location }}"
        name: "{{ deploy_group_name }}"

    # Create or update a template deployment based on uris using parameter and template links
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        location: "{{ deploy_group_location }}"
        resource_group_name: "{{ deploy_group_name }}"
        parameters:
            vmadminUsername: 
              value: "{{ vm_admin_username }}"
            vmadminPassword: 
              value: "{{ vm_admin_password }}"
        template_link: 'https://raw.githubusercontent.com/groovy-sky/azure/master/ansible-tower-00/azuredeploy.json'
      register: azure_deployment_results

    - name: Install ansible-tower-cli
      pip:
        name: ansible-tower-cli

    - name: Add tower host
      tower_host:
        name: "{{ azure_deployment_results.deployment.instances[0].ips[0].dns_settings.fqdn }}"
        inventory: "{{ awx_inevntory }}"
        state: present
